# Generated by Django 4.0.4 on 2022-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ENC', 'Encrypted'), ('DEC', 'Decrypted'), ('DEL', 'Deleted')], default='ENC', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
